### ISSUE TITLE
Exception when trying to Clone a Textmate's "LAZY" theme

### ISSUE THREAD

**Issue by alfuken** [sudoaugustin/vslook#5]
Exception when trying to Clone a Textmate's "LAZY" theme:

🚫 SyntaxError: JSON5: invalid character '<' at 1:1
	at syntaxError (/Users/bohdan/.vscode/extensions/sudoaugustin.vslook-0.3.1/node_modules/json5/lib/parse.js:1083:17)
	at invalidChar (/Users/bohdan/.vscode/extensions/sudoaugustin.vslook-0.3.1/node_modules/json5/lib/parse.js:1028:12)
	at Object.value (/Users/bohdan/.vscode/extensions/sudoaugustin.vslook-0.3.1/node_modules/json5/lib/parse.js:287:15)
	at lex (/Users/bohdan/.vscode/extensions/sudoaugustin.vslook-0.3.1/node_modules/json5/lib/parse.js:78:42)
	at Object.parse (/Users/bohdan/.vscode/extensions/sudoaugustin.vslook-0.3.1/node_modules/json5/lib/parse.js:25:17)
	at Object.read (/Users/bohdan/.vscode/extensions/sudoaugustin.vslook-0.3.1/src/utils/fs.js:7:30)
	at /Users/bohdan/.vscode/extensions/sudoaugustin.vslook-0.3.1/src/theme.js:95:33
	at _withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:45034)
	at _.withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:44788)
	at Object.withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:42345)
	at /Users/bohdan/.vscode/extensions/sudoaugustin.vslook-0.3.1/src/theme.js:94:14
	at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by sudoaugustin** [comment]
There are [two approaches](https://code.visualstudio.com/api/extension-guides/color-theme#syntax-colors) in vscode syntax theming. VSLook only works with `.json` theme. The LAZY used `.tmTheme` and VSLook doesn't support that.

<img width="773" alt="Screen Shot 2022-07-24 at 7 11 38 PM" src="https://user-images.githubusercontent.com/57541158/180647601-44f0b07b-03f2-4387-871d-4edf9efcca74.png">
